/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as PublicCoursesIdRouteImport } from './routes/_public/courses/$id'
import { Route as ProtectedDashboardCoursesIndexRouteImport } from './routes/_protected/dashboard/courses/index'
import { Route as ProtectedAdminDashboardIndexRouteImport } from './routes/_protected/admin/dashboard/index'
import { Route as ProtectedDashboardCoursesSlugRouteImport } from './routes/_protected/dashboard/courses/$slug'
import { Route as ProtectedAdminDashboardCoursesIndexRouteImport } from './routes/_protected/admin/dashboard/courses/index'
import { Route as ProtectedAdminDashboardCoursesNewRouteImport } from './routes/_protected/admin/dashboard/courses/new'
import { Route as ProtectedAdminDashboardCoursesSlugEditRouteImport } from './routes/_protected/admin/dashboard/courses/$slug/edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicCoursesIdRoute = PublicCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedDashboardCoursesIndexRoute =
  ProtectedDashboardCoursesIndexRouteImport.update({
    id: '/dashboard/courses/',
    path: '/dashboard/courses/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminDashboardIndexRoute =
  ProtectedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedDashboardCoursesSlugRoute =
  ProtectedDashboardCoursesSlugRouteImport.update({
    id: '/dashboard/courses/$slug',
    path: '/dashboard/courses/$slug',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminDashboardCoursesIndexRoute =
  ProtectedAdminDashboardCoursesIndexRouteImport.update({
    id: '/dashboard/courses/',
    path: '/dashboard/courses/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminDashboardCoursesNewRoute =
  ProtectedAdminDashboardCoursesNewRouteImport.update({
    id: '/dashboard/courses/new',
    path: '/dashboard/courses/new',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminDashboardCoursesSlugEditRoute =
  ProtectedAdminDashboardCoursesSlugEditRouteImport.update({
    id: '/dashboard/courses/$slug/edit',
    path: '/dashboard/courses/$slug/edit',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/courses/$id': typeof PublicCoursesIdRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/dashboard/courses/$slug': typeof ProtectedDashboardCoursesSlugRoute
  '/admin/dashboard/': typeof ProtectedAdminDashboardIndexRoute
  '/dashboard/courses/': typeof ProtectedDashboardCoursesIndexRoute
  '/admin/dashboard/courses/new': typeof ProtectedAdminDashboardCoursesNewRoute
  '/admin/dashboard/courses/': typeof ProtectedAdminDashboardCoursesIndexRoute
  '/admin/dashboard/courses/$slug/edit': typeof ProtectedAdminDashboardCoursesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/courses/$id': typeof PublicCoursesIdRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/courses/$slug': typeof ProtectedDashboardCoursesSlugRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardIndexRoute
  '/dashboard/courses': typeof ProtectedDashboardCoursesIndexRoute
  '/admin/dashboard/courses/new': typeof ProtectedAdminDashboardCoursesNewRoute
  '/admin/dashboard/courses': typeof ProtectedAdminDashboardCoursesIndexRoute
  '/admin/dashboard/courses/$slug/edit': typeof ProtectedAdminDashboardCoursesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/courses/$id': typeof PublicCoursesIdRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dashboard/courses/$slug': typeof ProtectedDashboardCoursesSlugRoute
  '/_protected/admin/dashboard/': typeof ProtectedAdminDashboardIndexRoute
  '/_protected/dashboard/courses/': typeof ProtectedDashboardCoursesIndexRoute
  '/_protected/admin/dashboard/courses/new': typeof ProtectedAdminDashboardCoursesNewRoute
  '/_protected/admin/dashboard/courses/': typeof ProtectedAdminDashboardCoursesIndexRoute
  '/_protected/admin/dashboard/courses/$slug/edit': typeof ProtectedAdminDashboardCoursesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/courses/$id'
    | '/dashboard/'
    | '/dashboard/courses/$slug'
    | '/admin/dashboard/'
    | '/dashboard/courses/'
    | '/admin/dashboard/courses/new'
    | '/admin/dashboard/courses/'
    | '/admin/dashboard/courses/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/courses/$id'
    | '/dashboard'
    | '/dashboard/courses/$slug'
    | '/admin/dashboard'
    | '/dashboard/courses'
    | '/admin/dashboard/courses/new'
    | '/admin/dashboard/courses'
    | '/admin/dashboard/courses/$slug/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_protected/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/_public/'
    | '/_public/courses/$id'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/courses/$slug'
    | '/_protected/admin/dashboard/'
    | '/_protected/dashboard/courses/'
    | '/_protected/admin/dashboard/courses/new'
    | '/_protected/admin/dashboard/courses/'
    | '/_protected/admin/dashboard/courses/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/courses/$id': {
      id: '/_public/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof PublicCoursesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/dashboard/courses/': {
      id: '/_protected/dashboard/courses/'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof ProtectedDashboardCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/dashboard/': {
      id: '/_protected/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof ProtectedAdminDashboardIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/dashboard/courses/$slug': {
      id: '/_protected/dashboard/courses/$slug'
      path: '/dashboard/courses/$slug'
      fullPath: '/dashboard/courses/$slug'
      preLoaderRoute: typeof ProtectedDashboardCoursesSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/dashboard/courses/': {
      id: '/_protected/admin/dashboard/courses/'
      path: '/dashboard/courses'
      fullPath: '/admin/dashboard/courses/'
      preLoaderRoute: typeof ProtectedAdminDashboardCoursesIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/dashboard/courses/new': {
      id: '/_protected/admin/dashboard/courses/new'
      path: '/dashboard/courses/new'
      fullPath: '/admin/dashboard/courses/new'
      preLoaderRoute: typeof ProtectedAdminDashboardCoursesNewRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/dashboard/courses/$slug/edit': {
      id: '/_protected/admin/dashboard/courses/$slug/edit'
      path: '/dashboard/courses/$slug/edit'
      fullPath: '/admin/dashboard/courses/$slug/edit'
      preLoaderRoute: typeof ProtectedAdminDashboardCoursesSlugEditRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminDashboardIndexRoute: typeof ProtectedAdminDashboardIndexRoute
  ProtectedAdminDashboardCoursesNewRoute: typeof ProtectedAdminDashboardCoursesNewRoute
  ProtectedAdminDashboardCoursesIndexRoute: typeof ProtectedAdminDashboardCoursesIndexRoute
  ProtectedAdminDashboardCoursesSlugEditRoute: typeof ProtectedAdminDashboardCoursesSlugEditRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminDashboardIndexRoute: ProtectedAdminDashboardIndexRoute,
  ProtectedAdminDashboardCoursesNewRoute:
    ProtectedAdminDashboardCoursesNewRoute,
  ProtectedAdminDashboardCoursesIndexRoute:
    ProtectedAdminDashboardCoursesIndexRoute,
  ProtectedAdminDashboardCoursesSlugEditRoute:
    ProtectedAdminDashboardCoursesSlugEditRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardCoursesSlugRoute: typeof ProtectedDashboardCoursesSlugRoute
  ProtectedDashboardCoursesIndexRoute: typeof ProtectedDashboardCoursesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardCoursesSlugRoute: ProtectedDashboardCoursesSlugRoute,
  ProtectedDashboardCoursesIndexRoute: ProtectedDashboardCoursesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesIdRoute: typeof PublicCoursesIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesIdRoute: PublicCoursesIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
